# docker-compose-hom.yml - Ambiente de Homologação (2 nós)
version: '3.9'

services:
  eureka-hom-node1:
    build: .
    container_name: ${HOM_NODE1_HOSTNAME}
    hostname: ${HOM_NODE1_HOSTNAME}
    environment:
      - SPRING_PROFILES_ACTIVE=hom
      - HOSTNAME=${HOM_NODE1_HOSTNAME}
      - HOST_IP=${HOM_NODE1_IP}
    ports:
      - "8761:8761"
    networks:
      eureka-net:
        ipv4_address: ${HOM_NODE1_IP}

  eureka-hom-node2:
    build: .
    container_name: ${HOM_NODE2_HOSTNAME}
    hostname: ${HOM_NODE2_HOSTNAME}
    environment:
      - SPRING_PROFILES_ACTIVE=hom
      - HOSTNAME=${HOM_NODE2_HOSTNAME}
      - HOST_IP=${HOM_NODE2_IP}
    ports:
      - "8762:8761"
    networks:
      eureka-net:
        ipv4_address: ${HOM_NODE2_IP}

networks:
  eureka-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
