# infra-domain/docker-compose.yml
services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - taptrack-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev,h2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - taptrack-network

  h2:
    image: oscarfonts/h2
    container_name: h2
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - taptrack-network

networks:
  taptrack-network:
    driver: bridge