version: "3.9"

networks:
  microservices-net:
    driver: bridge
  # Rede externa
  shared-microservices-network:
    external: true

services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - APP_PORT=8888
      - JAVA_OPTS=-Xms128m -Xmx512m
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASS}
    networks:
      - microservices-net
      - shared-microservices-network # Conecte a rede externa
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      retries: 10
      start_period: 10s

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - APP_PORT=8761
      - JAVA_OPTS=-Xms128m -Xmx512m
    networks:
      - microservices-net
      - shared-microservices-network # Conecte a rede externa
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      retries: 10
      start_period: 10s

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - JAVA_OPTS=-Xms128m -Xmx512m
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    networks:
      - microservices-net
      - shared-microservices-network # Conecte a rede externa
    depends_on:
      discovery-service:
        condition: service_healthy