# infra-domain/docker-compose.yml
networks:
  taptrack-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  eureka-server:
    image: eureka-server
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - APP_PORT=8761
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8761/eureka/apps" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      taptrack-net:
        ipv4_address: 172.20.0.2

  api-gateway:
    image: api-gateway
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,h2
      - JAVA_OPTS=-Xms256m -Xmx512m
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.20.0.2:8761/eureka/
      - APP_PORT=8080
    networks:
      taptrack-net:
        ipv4_address: 172.20.0.3
