# ============================================
# Configurações Globais - application.yml
# ============================================

spring:
  application:
    name: global-config
  profiles:
    active: dev

# --- Logging padrão ---
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.netflix.discovery: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# --- Configurações comuns do Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

# --- Configuração CORS padrão ---
#cors:
#  allowed-origins: "http://localhost:4200"
#  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#  allowed-headers: "*"
#  allow-credentials: true

# --- Informações Globais ---
info:
  app:
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com
    license: Apache-2.0
    environment: local
