server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true       # ✅ registra-se no Eureka
    fetch-registry: true             # ✅ busca outros serviços
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10      # envia heartbeat a cada 10s
    lease-expiration-duration-in-seconds: 30   # expira se 3 batimentos forem perdidos
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
