server:
  port: 8080

spring:
  application:
    name: gateway-service

# --- Eureka ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
          - httptrace
          - env
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    enable:
      all: true

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud.gateway: DEBUG
    com.infradomain.gatewayservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

debug: true