# --- Gateway Server ---
# application.yml
#
server:
  port: 8080

spring:
  application:
    name: gateway-service

# --- Eureka ---
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,env
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    enable:
      all: true

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.infradomain.gatewayservice: DEBUG

info:
  app:
    name: ${spring.application.name}
    description: API Gateway do sistema TapTrack
    version: 0.0.1-SNAPSHOT
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com
