# application.yml
# Porta
server:
  port: 8761

# Eureka Server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
  instance:
    hostname: discovery-service

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.infra_domain.discoveryservice: DEBUG
    org.springframework.cloud: INFO
