# --- Discovery Server ---
# application.yml
#
server:
  port: 8761

spring:
  application:
    name: discovery-service

# --- Eureka Server ---
eureka:
  client:
    register-with-eureka: false  # servidor não se registra
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,env
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    enable:
      all: true
  info:
    git:
      mode: full

# --- Info ---
info:
  app:
    name: ${spring.application.name}
    description: Service registry using Spring Cloud Eureka
    version: 1.0.0
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com
    license: Apache-2.0
    homepage: https://github.com/taptrack-system/infra-domain
  build:
    artifact: ${spring.application.name}
    version: 1.0.0
    time: ${BUILD_TIME:2025-09-27T00:00:00Z}   # opcional, pode ser gerado pelo Maven
    commit: ${GIT_COMMIT:unknown}
  environment:
    activeProfiles: ${spring.profiles.active:default}
    javaVersion: ${java.version}
    os: ${os.name}

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.netflix.discovery: WARN         # Eureka / Discovery
    com.infradomain.discoveryservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"