# --- Discovery Server ---
# application.yml
#
server:
  port: 8761

spring:
  application:
    name: discovery-service
  cache:
    type: caffeine
    cache-names:
      - routesCache
      - usersCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m,recordStats

# --- Eureka Server ---
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# --- Logging ---
logging:
  level:
    root: INFO
    com.infradomain.discoveryservice: DEBUG
    org.springframework.cache: DEBUG
    com.netflix.discovery: WARN

info:
  app:
    name: ${spring.application.name}
    description: Service registry using Spring Cloud Eureka
    version: 1.0.0
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com