# application.yml
# --- Config Server ---
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/taptrack-system/config-repo.git
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:./config-repo


# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,metrics
  endpoint:
    health:
      show-details: always

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    org.springframework.boot.actuate: INFO
    org.springframework.cloud.config.server: DEBUG
    org.springframework.web: INFO
    com.infradomain.configservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/config-service.log