# ============================================
# Config Service - application.yml
# ============================================

spring:
  application:
    name: config-service
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./config-repo
            - file:./config-repo/infra-domain
            - file:./config-repo/identity-access-domain
            - file:./config-repo/finance-domain
            - file:./config-repo/supplier-domain
            - file:./config-repo/product-beer-domain
            - file:./config-repo/tap-pos-domain
      fail-fast: true

server:
  port: 8888

# --- Logging ---
logging:
  level:
    root: INFO
    com.infradomain.configservice: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

# --- Informações da aplicação ---
info:
  app:
    name: Config Service
    description: Servidor Central de Configuração do Sistema TapTrack
    version: 0.0.1-SNAPSHOT
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com
    license: Apache-2.0
  build:
    version: 1.0.0
    time: ${BUILD_TIME:2025-10-07T00:00:00Z}
    commit: ${GIT_COMMIT:local}
  environment:
    activeProfiles: ${spring.profiles.active:default}
    javaVersion: ${java.version}
    os: ${os.name}
