# --- Config Server ---
# application.yml
#
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/taptrack-system/config-repo.git
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASS}
  cache:
    type: caffeine
    cache-names:
      - routesCache
      - usersCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m,recordStats

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,env
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    enable:
      all: true
  info:
    git:
      mode: full

# --- Info ---
info:
  app:
    name: ${spring.application.name}
    description: Centralized configuration service using Spring Cloud Config
    version: 1.0.0
    maintainer: Juliane Maran
    contact: julianemaran@gmail.com
    license: Apache-2.0
    homepage: https://github.com/taptrack-system/infra-domain
  build:
    artifact: ${spring.application.name}
    version: 1.0.0
    time: ${BUILD_TIME:2025-09-27T00:00:00Z}   # opcional, pode ser gerado pelo Maven
    commit: ${GIT_COMMIT:unknown}
  environment:
    activeProfiles: ${spring.profiles.active:default}
    javaVersion: ${java.version}
    os: ${os.name}

# --- Logging ---
logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.infradomain.configservice: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
